version: "3.7"

services:
  app:
    container_name: "readytotouch_go_app"
    image: golang:1.21.0-alpine
    working_dir: /go/src/github.com/readytotouch-yaaws/yaaws-go
    volumes:
      - .:/go/src/github.com/readytotouch-yaaws/yaaws-go
    command: "sleep 1d"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres

  postgres:
    container_name: "readytotouch_postgres_db"
    image: postgres:15.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/volumes/postgresql/data/:/var/lib/postgresql/data/
